// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuscleTrainingApi.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MuscleTrainingApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830115720_AddCardioOwnership")]
    partial class AddCardioOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MuscleTrainingApi.Models.Cardio", b =>
                {
                    b.Property<int>("Cardio_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Cardio_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cardio_Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("now()");

                    b.Property<double?>("Distance_Km")
                        .HasColumnType("double precision")
                        .HasColumnName("Distance_Km");

                    b.Property<int>("Duration_Min")
                        .HasColumnType("integer")
                        .HasColumnName("Duration_Min");

                    b.Property<string>("Exercise_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Exercise_Name");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.HasKey("Cardio_Id");

                    b.HasIndex("User_Id", "CreatedAt")
                        .HasDatabaseName("IX_Cardio_User_CreatedAt");

                    b.ToTable("Cardio", "public");
                });

            modelBuilder.Entity("MuscleTrainingApi.Models.Category", b =>
                {
                    b.Property<int>("Category_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Category_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Category_Id"));

                    b.Property<string>("Category_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("Category_Name");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.HasKey("Category_Id");

                    b.HasIndex("User_Id", "Category_Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Categories_User_Name");

                    b.ToTable("Categories", "public");
                });

            modelBuilder.Entity("MuscleTrainingApi.Models.Exercise", b =>
                {
                    b.Property<int>("Exercise_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Exercise_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Exercise_Id"));

                    b.Property<int>("Category_Id")
                        .HasColumnType("integer")
                        .HasColumnName("Category_Id");

                    b.Property<string>("Exercise_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Exercise_Name");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.HasKey("Exercise_Id");

                    b.HasIndex("Category_Id");

                    b.HasIndex("User_Id", "Category_Id", "Exercise_Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Exercises_User_Cat_Name");

                    b.ToTable("Exercises", "public");
                });

            modelBuilder.Entity("MuscleTrainingApi.Models.User", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Password_Hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("User_Name");

                    b.HasKey("User_Id");

                    b.ToTable("Users", "public");
                });

            modelBuilder.Entity("MuscleTrainingApi.Models.Workout", b =>
                {
                    b.Property<int>("Record_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Record_Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Record_Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("Exercise_Id")
                        .HasColumnType("integer")
                        .HasColumnName("Exercise_Id");

                    b.Property<int>("Reps")
                        .HasColumnType("integer")
                        .HasColumnName("Reps");

                    b.Property<int>("User_Id")
                        .HasColumnType("integer")
                        .HasColumnName("User_Id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("Weight");

                    b.HasKey("Record_Id");

                    b.HasIndex("Exercise_Id");

                    b.HasIndex("User_Id", "CreatedAt")
                        .HasDatabaseName("IX_Workout_User_CreatedAt");

                    b.ToTable("Workout", "public");
                });

            modelBuilder.Entity("MuscleTrainingApi.Models.Cardio", b =>
                {
                    b.HasOne("MuscleTrainingApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuscleTrainingApi.Models.Category", b =>
                {
                    b.HasOne("MuscleTrainingApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuscleTrainingApi.Models.Exercise", b =>
                {
                    b.HasOne("MuscleTrainingApi.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("Category_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MuscleTrainingApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuscleTrainingApi.Models.Workout", b =>
                {
                    b.HasOne("MuscleTrainingApi.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("Exercise_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MuscleTrainingApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
